import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const context={products:[],document:{addEventListener(){}},esc:String,$(){return{};}};vm.createContext(context);vm.runInContext(fs.readFileSync('catalog-inventory.js','utf8'),context);
assert.equal(typeof context.catalogProductIssues,'function');
assert.deepEqual(Array.from(context.catalogProductIssues({name:'',sku:'',source:{category:'machines'}})),['Product name is missing','SKU / part number is missing','Machine company is missing','Machine model is missing']);
assert.deepEqual(Array.from(context.catalogProductIssues({name:'Reagent A',sku:'R-1',source:{category:'reagents',machine_ids:[]}})),['No compatible machine is linked']);
assert.deepEqual(Array.from(context.catalogProductIssues({name:'Machine A',sku:'M-1',source:{category:'machines',company:'Maker',model:'X'}})),[]);
assert.deepEqual(JSON.parse(JSON.stringify(context.catalogNameClues('Chemistry Analyzer Reagent pack of 50'))),{suggestedCategory:'reagents',categoryReason:'Item name explicitly says reagent',packHint:'pack of 50'});
assert.equal(context.catalogNameClues('Chemistry Analyzer Spare').suggestedCategory,'spares');
assert.equal(context.catalogNameClues('Coagulation Machine Service').suggestedCategory,'non_stock');
assert.equal(context.catalogNameClues('Adult Electrode Bracket 5 Pcs Bags').packHint,'5 Pcs Bags');
assert.equal(context.catalogNameClues('A D E Analyzer Model MZ 10020').suggestedCategory,'machines');
assert.equal(context.catalogNameClues('Ordinary Item 123').suggestedCategory,'');
console.log('PASS: inventory review flags incomplete machine and related-product master data.');
