import assert from 'node:assert/strict';
import fs from 'node:fs';

const source=fs.readFileSync('sales-delivery.js','utf8'),html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8');
assert.match(html,/data-view="sales">Pro forma &amp; delivery/);
assert.match(html,/sales-domain\.js/);
assert.match(html,/sales-delivery\.js/);
assert.match(app,/view==='sales'.*salesDeliveryWorkspace/);
assert.match(source,/Pro forma submitted/);
assert.match(source,/Accounts approved/);
assert.match(source,/Tax invoice created/);
assert.match(source,/Sent to downstairs sales/);
assert.match(source,/Packing in progress/);
assert.match(source,/Ready for delivery/);
assert.match(source,/Out for delivery/);
assert.match(source,/Delivery note signed/);
assert.match(source,/workflow-progress/);
assert.match(source,/save_sales_proforma/);
assert.match(source,/advance_sales_proforma/);
assert.match(source,/create_sales_delivery_note/);
assert.match(source,/advance_sales_delivery/);
assert.match(source,/Print \/ PDF/);
assert.match(source,/No loose Haadi stock is available for this item/);
assert.match(source,/Accounts approval does not depend on stock availability/);
assert.match(source,/start_sales_delivery_packing/);
assert.doesNotMatch(source,/>Dispatch \/ out for delivery</);
assert.match(source,/equipment-handover-installation-report\.pdf/);
assert.match(source,/service-work-report\.pdf/);
assert.match(source,/Official forms & PDFs/);
console.log('PASS: team UI exposes the guarded Pro forma-to-delivery workflow and printable records.');
